image: docker:stable

services:
    - docker:stable-dind

variables:
    REPOSITORY: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}"
    OS: "${CI_COMMIT_REF_NAME}"

before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_TOKEN}"

stages:
    - cuda
    - cudnn
    - trigger

.cuda_template: &cuda_definition
    stage: cuda
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --label "com.nvidia.build.ref=${CI_COMMIT_SHA}"
                   --label "com.nvidia.build.id=${CI_JOB_ID}"
                   "${VERSION}/runtime"
    - docker build -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${VERSION}/devel"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - if [[ "${LATEST}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:latest";
      fi
    - docker push "${REPOSITORY}"

.cudnn_template: &cudnn_definition
    stage: cudnn
    script:
    - VERSION="${CI_JOB_NAME:1}"
    - CUDA_VERSION="${CI_JOB_NAME:1:3}"
    - CUDNN_VERSION="${CI_JOB_NAME:5}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-runtime-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/runtime/${CUDNN_VERSION}"
    - docker build --pull -t "${REPOSITORY}:${VERSION}-devel-${OS}"
                   --build-arg "repository=${REPOSITORY}"
                   "${CUDA_VERSION}/devel/${CUDNN_VERSION}"
    - if [[ "${NO_OS_SUFFIX}" == true ]]; then
          docker tag "${REPOSITORY}:${VERSION}-runtime-${OS}" "${REPOSITORY}:${VERSION}-runtime";
          docker tag "${REPOSITORY}:${VERSION}-devel-${OS}" "${REPOSITORY}:${VERSION}-devel";
      fi
    - docker push "${REPOSITORY}"

v6.5:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_definition

v7.0:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_definition

v7.0-cudnn2:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.0-cudnn3:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.0-cudnn4:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.5:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cuda_definition

v7.5-cudnn3:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.5-cudnn4:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.5-cudnn5:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v7.5-cudnn6:
    variables:
        NO_OS_SUFFIX: "true"
    <<: *cudnn_definition

v8.0:
    <<: *cuda_definition

v8.0-cudnn5:
    <<: *cudnn_definition

v8.0-cudnn6:
    <<: *cudnn_definition

v8.0-cudnn7:
    <<: *cudnn_definition

caffe:
    stage: trigger
    script:
    - apk add --no-cache curl
    - curl -fsS -X POST -F token="${CAFFE_TRIGGER_TOKEN}" -F ref="master" "${CAFFE_TRIGGER_URL}"
